name: Backend-Workflow
on: [push]
jobs:
  check-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: apt-get install docker-ce docker-ce-cli containerd.io
      - run: docker run  --publish=7474:7474 --publish=7687:7687 --env=NEO4J_AUTH=none neo4j:latest
      - run: npm install
      - run: npm run test
