name: Lint-Test-Status
on: [push]
jobs:
  check-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: webapp
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: webapp
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test:unit --verbose
